namespace BazaMvp.Migrations
{
    using BazaMvp.Model;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<BazaMvp.IFModel>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }
        
        protected override void Seed(BazaMvp.IFModel context)
        {
            context.Participants.AddOrUpdate(i => i.Name,
                new Participant { Name = "Dwustronna" },
                new Participant { Name = "Trojstronna" },
                new Participant { Name = "Gotowka" },
                new Participant { Name = "eCommerce" },
                new Participant { Name = "Spencer IE" },
                new Participant { Name = "Spencer UK" },
                new Participant { Name = "Revo PL" },
                new Participant { Name = "CBA" },
                new Participant { Name = "Tracy" }
                );
            context.SaveChanges();
            context.VisaImportRules.AddOrUpdate(r => r.ReportingFor,
                new VisaImportRule { ReportingFor = "1000072345", Participant = context.Participants.FirstOrDefault(p => p.Name == "Dwustronna") },
                new VisaImportRule { ReportingFor = "3571836572", Participant = context.Participants.FirstOrDefault(p => p.Name == "Dwustronna") },
                new VisaImportRule { ReportingFor = "1000072343", Participant = context.Participants.FirstOrDefault(p => p.Name == "Dwustronna") },
                new VisaImportRule { ReportingFor = "7317119863", Participant = context.Participants.FirstOrDefault(p => p.Name == "Dwustronna") },
                new VisaImportRule { ReportingFor = "7512352372", Participant = context.Participants.FirstOrDefault(p => p.Name == "Dwustronna") },
                new VisaImportRule { ReportingFor = "3188225036", Participant = context.Participants.FirstOrDefault(p => p.Name == "Trojstronna") },
                new VisaImportRule { ReportingFor = "3950067011", Participant = context.Participants.FirstOrDefault(p => p.Name == "Trojstronna") },
                new VisaImportRule { ReportingFor = "3717925979", Participant = context.Participants.FirstOrDefault(p => p.Name == "Trojstronna") },
                new VisaImportRule { ReportingFor = "3780501353", Participant = context.Participants.FirstOrDefault(p => p.Name == "Trojstronna") },
                new VisaImportRule { ReportingFor = "1000112466", Participant = context.Participants.FirstOrDefault(p => p.Name == "Gotowka") },
                new VisaImportRule { ReportingFor = "1000112467", Participant = context.Participants.FirstOrDefault(p => p.Name == "Gotowka") },
                new VisaImportRule { ReportingFor = "7925462225", Participant = context.Participants.FirstOrDefault(p => p.Name == "eCommerce") },
                new VisaImportRule { ReportingFor = "7607485172", Participant = context.Participants.FirstOrDefault(p => p.Name == "eCommerce") },
                new VisaImportRule { ReportingFor = "7687516196", Participant = context.Participants.FirstOrDefault(p => p.Name == "eCommerce") },
                new VisaImportRule { ReportingFor = "7900320376", Participant = context.Participants.FirstOrDefault(p => p.Name == "eCommerce") },
                new VisaImportRule { ReportingFor = "7198043846", Participant = context.Participants.FirstOrDefault(p => p.Name == "eCommerce") },
                new VisaImportRule { ReportingFor = "7421837706", Participant = context.Participants.FirstOrDefault(p => p.Name == "eCommerce") },
                new VisaImportRule { ReportingFor = "7033744635", Participant = context.Participants.FirstOrDefault(p => p.Name == "Spencer IE") },
                new VisaImportRule { ReportingFor = "7258886033", Participant = context.Participants.FirstOrDefault(p => p.Name == "Spencer IE") },
                new VisaImportRule { ReportingFor = "7498597162", Participant = context.Participants.FirstOrDefault(p => p.Name == "Spencer UK") },
                new VisaImportRule { ReportingFor = "7790786732", Participant = context.Participants.FirstOrDefault(p => p.Name == "Spencer UK") },
                new VisaImportRule { ReportingFor = "7325663183", Participant = context.Participants.FirstOrDefault(p => p.Name == "Revo PL") },
                new VisaImportRule { ReportingFor = "7221247453", Participant = context.Participants.FirstOrDefault(p => p.Name == "Revo PL") },
                new VisaImportRule { ReportingFor = "3230126899", Participant = context.Participants.FirstOrDefault(p => p.Name == "CBA") },
                new VisaImportRule { ReportingFor = "3590127630", Participant = context.Participants.FirstOrDefault(p => p.Name == "CBA") },
                new VisaImportRule { ReportingFor = "3938085668", Participant = context.Participants.FirstOrDefault(p => p.Name == "CBA") },
                new VisaImportRule { ReportingFor = "3242258861", Participant = context.Participants.FirstOrDefault(p => p.Name == "CBA") },
                new VisaImportRule { ReportingFor = "3978035493", Participant = context.Participants.FirstOrDefault(p => p.Name == "CBA") },
                new VisaImportRule { ReportingFor = "3936249583", Participant = context.Participants.FirstOrDefault(p => p.Name == "CBA") },
                new VisaImportRule { ReportingFor = "7723213063", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "7867981231", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "7014483295", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "7274530397", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "7605191367", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "7792090160", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "7867419356", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3094819503", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3823606188", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3039576598", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3966277321", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3039444479", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3052364979", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3060548897", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3181135027", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3324435288", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3973315258", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3513185591", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3740119811", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3756527486", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3776628258", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3937597998", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3973449652", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3853939792", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3375564541", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") },
                new VisaImportRule { ReportingFor = "3188455428", Participant = context.Participants.FirstOrDefault(p => p.Name == "Tracy") }
                );

            context.CurrencyCodes.AddOrUpdate(c => c.Code,
                new CurrencyCode { Code = "AED", NumCode = "784", Name = "United Arab Emirates dirham" },
                new CurrencyCode { Code = "AFN", NumCode = "971", Name = "Afghan afghani" },
                new CurrencyCode { Code = "ALL", NumCode = "8", Name = "Albanian lek" },
                new CurrencyCode { Code = "AMD", NumCode = "51", Name = "Armenian dram" },
                new CurrencyCode { Code = "ANG", NumCode = "532", Name = "Netherlands Antillean guilder" },
                new CurrencyCode { Code = "AOA", NumCode = "973", Name = "Angolan kwanza" },
                new CurrencyCode { Code = "ARS", NumCode = "32", Name = "Argentine peso" },
                new CurrencyCode { Code = "AUD", NumCode = "36", Name = "Australian dollar" },
                new CurrencyCode { Code = "AWG", NumCode = "533", Name = "Aruban guilder" },
                new CurrencyCode { Code = "AZN", NumCode = "944", Name = "Azerbaijani manat" },
                new CurrencyCode { Code = "BAM", NumCode = "977", Name = "Bosnia and Herzegovina convertible mark" },
                new CurrencyCode { Code = "BBD", NumCode = "52", Name = "Barbados dollar" },
                new CurrencyCode { Code = "BDT", NumCode = "50", Name = "Bangladeshi taka" },
                new CurrencyCode { Code = "BGN", NumCode = "975", Name = "Bulgarian lev" },
                new CurrencyCode { Code = "BHD", NumCode = "48", Name = "Bahraini dinar" },
                new CurrencyCode { Code = "BIF", NumCode = "108", Name = "Burundian franc" },
                new CurrencyCode { Code = "BMD", NumCode = "60", Name = "Bermudian dollar (customarily known as Bermuda dollar)" },
                new CurrencyCode { Code = "BND", NumCode = "96", Name = "Brunei dollar" },
                new CurrencyCode { Code = "BOB", NumCode = "68", Name = "Boliviano" },
                new CurrencyCode { Code = "BOV", NumCode = "984", Name = "Bolivian Mvdol (funds code)" },
                new CurrencyCode { Code = "BRL", NumCode = "986", Name = "Brazilian real" },
                new CurrencyCode { Code = "BSD", NumCode = "44", Name = "Bahamian dollar" },
                new CurrencyCode { Code = "BTN", NumCode = "64", Name = "Bhutanese ngultrum" },
                new CurrencyCode { Code = "BWP", NumCode = "72", Name = "Botswana pula" },
                new CurrencyCode { Code = "BYR", NumCode = "974", Name = "Belarusian ruble" },
                new CurrencyCode { Code = "BZD", NumCode = "84", Name = "Belize dollar" },
                new CurrencyCode { Code = "CAD", NumCode = "124", Name = "Canadian dollar" },
                new CurrencyCode { Code = "CDF", NumCode = "976", Name = "Congolese franc" },
                new CurrencyCode { Code = "CHE", NumCode = "947", Name = "WIR Bank (complementary currency)" },
                new CurrencyCode { Code = "CHF", NumCode = "756", Name = "Swiss franc" },
                new CurrencyCode { Code = "CHW", NumCode = "948", Name = "WIR Bank (complementary currency)" },
                new CurrencyCode { Code = "CLF", NumCode = "990", Name = "Unidad de Fomento (funds code)" },
                new CurrencyCode { Code = "CLP", NumCode = "152", Name = "Chilean peso" },
                new CurrencyCode { Code = "CNY", NumCode = "156", Name = "Chinese yuan" },
                new CurrencyCode { Code = "COP", NumCode = "170", Name = "Colombian peso" },
                new CurrencyCode { Code = "COU", NumCode = "970", Name = "Unidad de Valor Real" },
                new CurrencyCode { Code = "CRC", NumCode = "188", Name = "Costa Rican colon" },
                new CurrencyCode { Code = "CUC", NumCode = "931", Name = "Cuban convertible peso" },
                new CurrencyCode { Code = "CUP", NumCode = "192", Name = "Cuban peso" },
                new CurrencyCode { Code = "CVE", NumCode = "132", Name = "Cape Verde escudo" },
                new CurrencyCode { Code = "CZK", NumCode = "203", Name = "Czech koruna" },
                new CurrencyCode { Code = "DJF", NumCode = "262", Name = "Djiboutian franc" },
                new CurrencyCode { Code = "DKK", NumCode = "208", Name = "Danish krone" },
                new CurrencyCode { Code = "DOP", NumCode = "214", Name = "Dominican peso" },
                new CurrencyCode { Code = "DZD", NumCode = "12", Name = "Algerian dinar" },
                new CurrencyCode { Code = "EEK", NumCode = "233", Name = "Estonian kroon" },
                new CurrencyCode { Code = "EGP", NumCode = "818", Name = "Egyptian pound" },
                new CurrencyCode { Code = "ERN", NumCode = "232", Name = "Eritrean nakfa" },
                new CurrencyCode { Code = "ETB", NumCode = "230", Name = "Ethiopian birr" },
                new CurrencyCode { Code = "EUR", NumCode = "978", Name = "Euro" },
                new CurrencyCode { Code = "FJD", NumCode = "242", Name = "Fiji dollar" },
                new CurrencyCode { Code = "FKP", NumCode = "238", Name = "Falkland Islands pound" },
                new CurrencyCode { Code = "GBP", NumCode = "826", Name = "Pound sterling" },
                new CurrencyCode { Code = "GEL", NumCode = "981", Name = "Georgian lari" },
                new CurrencyCode { Code = "GHS", NumCode = "936", Name = "Ghanaian cedi" },
                new CurrencyCode { Code = "GIP", NumCode = "292", Name = "Gibraltar pound" },
                new CurrencyCode { Code = "GMD", NumCode = "270", Name = "Gambian dalasi" },
                new CurrencyCode { Code = "GNF", NumCode = "324", Name = "Guinean franc" },
                new CurrencyCode { Code = "GTQ", NumCode = "320", Name = "Guatemalan quetzal" },
                new CurrencyCode { Code = "GYD", NumCode = "328", Name = "Guyanese dollar" },
                new CurrencyCode { Code = "HKD", NumCode = "344", Name = "Hong Kong dollar" },
                new CurrencyCode { Code = "HNL", NumCode = "340", Name = "Honduran lempira" },
                new CurrencyCode { Code = "HRK", NumCode = "191", Name = "Croatian kuna" },
                new CurrencyCode { Code = "HTG", NumCode = "332", Name = "Haitian gourde" },
                new CurrencyCode { Code = "HUF", NumCode = "348", Name = "Hungarian forint" },
                new CurrencyCode { Code = "IDR", NumCode = "360", Name = "Indonesian rupiah" },
                new CurrencyCode { Code = "ILS", NumCode = "376", Name = "Israeli new sheqel" },
                new CurrencyCode { Code = "INR", NumCode = "356", Name = "Indian rupee" },
                new CurrencyCode { Code = "IQD", NumCode = "368", Name = "Iraqi dinar" },
                new CurrencyCode { Code = "IRR", NumCode = "364", Name = "Iranian rial" },
                new CurrencyCode { Code = "ISK", NumCode = "352", Name = "Icelandic króna" },
                new CurrencyCode { Code = "JMD", NumCode = "388", Name = "Jamaican dollar" },
                new CurrencyCode { Code = "JOD", NumCode = "400", Name = "Jordanian dinar" },
                new CurrencyCode { Code = "JPY", NumCode = "392", Name = "Japanese yen" },
                new CurrencyCode { Code = "KES", NumCode = "404", Name = "Kenyan shilling" },
                new CurrencyCode { Code = "KGS", NumCode = "417", Name = "Kyrgyzstani som" },
                new CurrencyCode { Code = "KHR", NumCode = "116", Name = "Cambodian riel" },
                new CurrencyCode { Code = "KMF", NumCode = "174", Name = "Comoro franc" },
                new CurrencyCode { Code = "KPW", NumCode = "408", Name = "North Korean won" },
                new CurrencyCode { Code = "KRW", NumCode = "410", Name = "South Korean won" },
                new CurrencyCode { Code = "KWD", NumCode = "414", Name = "Kuwaiti dinar" },
                new CurrencyCode { Code = "KYD", NumCode = "136", Name = "Cayman Islands dollar" },
                new CurrencyCode { Code = "KZT", NumCode = "398", Name = "Kazakhstani tenge" },
                new CurrencyCode { Code = "LAK", NumCode = "418", Name = "Lao kip" },
                new CurrencyCode { Code = "LBP", NumCode = "422", Name = "Lebanese pound" },
                new CurrencyCode { Code = "LKR", NumCode = "144", Name = "Sri Lanka rupee" },
                new CurrencyCode { Code = "LRD", NumCode = "430", Name = "Liberian dollar" },
                new CurrencyCode { Code = "LSL", NumCode = "426", Name = "Lesotho loti" },
                new CurrencyCode { Code = "LTL", NumCode = "440", Name = "Lithuanian litas" },
                new CurrencyCode { Code = "LVL", NumCode = "428", Name = "Latvian lats" },
                new CurrencyCode { Code = "LYD", NumCode = "434", Name = "Libyan dinar" },
                new CurrencyCode { Code = "MAD", NumCode = "504", Name = "Moroccan dirham" },
                new CurrencyCode { Code = "MDL", NumCode = "498", Name = "Moldovan leu" },
                new CurrencyCode { Code = "MGA", NumCode = "969", Name = "Malagasy ariary" },
                new CurrencyCode { Code = "MKD", NumCode = "807", Name = "Macedonian denar" },
                new CurrencyCode { Code = "MMK", NumCode = "104", Name = "Myanma kyat" },
                new CurrencyCode { Code = "MNT", NumCode = "496", Name = "Mongolian tugrik" },
                new CurrencyCode { Code = "MOP", NumCode = "446", Name = "Macanese pataca" },
                new CurrencyCode { Code = "MRO", NumCode = "478", Name = "Mauritanian ouguiya" },
                new CurrencyCode { Code = "MUR", NumCode = "480", Name = "Mauritian rupee" },
                new CurrencyCode { Code = "MVR", NumCode = "462", Name = "Maldivian rufiyaa" },
                new CurrencyCode { Code = "MWK", NumCode = "454", Name = "Malawian kwacha" },
                new CurrencyCode { Code = "MXN", NumCode = "484", Name = "Mexican peso" },
                new CurrencyCode { Code = "MXV", NumCode = "979", Name = "Mexican Unidad de Inversion (UDI) (funds code)" },
                new CurrencyCode { Code = "MYR", NumCode = "458", Name = "Malaysian ringgit" },
                new CurrencyCode { Code = "MZN", NumCode = "943", Name = "Mozambican metical" },
                new CurrencyCode { Code = "NAD", NumCode = "516", Name = "Namibian dollar" },
                new CurrencyCode { Code = "NGN", NumCode = "566", Name = "Nigerian naira" },
                new CurrencyCode { Code = "NIO", NumCode = "558", Name = "Cordoba oro" },
                new CurrencyCode { Code = "NOK", NumCode = "578", Name = "Norwegian krone" },
                new CurrencyCode { Code = "NPR", NumCode = "524", Name = "Nepalese rupee" },
                new CurrencyCode { Code = "NZD", NumCode = "554", Name = "New Zealand dollar" },
                new CurrencyCode { Code = "OMR", NumCode = "512", Name = "Omani rial" },
                new CurrencyCode { Code = "PAB", NumCode = "590", Name = "Panamanian balboa" },
                new CurrencyCode { Code = "PEN", NumCode = "604", Name = "Peruvian nuevo sol" },
                new CurrencyCode { Code = "PGK", NumCode = "598", Name = "Papua New Guinean kina" },
                new CurrencyCode { Code = "PHP", NumCode = "608", Name = "Philippine peso" },
                new CurrencyCode { Code = "PKR", NumCode = "586", Name = "Pakistani rupee" },
                new CurrencyCode { Code = "PLN", NumCode = "985", Name = "Polish z³oty" },
                new CurrencyCode { Code = "PYG", NumCode = "600", Name = "Paraguayan guaraní" },
                new CurrencyCode { Code = "QAR", NumCode = "634", Name = "Qatari rial" },
                new CurrencyCode { Code = "RON", NumCode = "946", Name = "Romanian new leu" },
                new CurrencyCode { Code = "RSD", NumCode = "941", Name = "Serbian dinar" },
                new CurrencyCode { Code = "RUB", NumCode = "643", Name = "Russian rouble" },
                new CurrencyCode { Code = "RWF", NumCode = "646", Name = "Rwandan franc" },
                new CurrencyCode { Code = "SAR", NumCode = "682", Name = "Saudi riyal" },
                new CurrencyCode { Code = "SBD", NumCode = "90", Name = "Solomon Islands dollar" },
                new CurrencyCode { Code = "SCR", NumCode = "690", Name = "Seychelles rupee" },
                new CurrencyCode { Code = "SDG", NumCode = "938", Name = "Sudanese pound" },
                new CurrencyCode { Code = "SEK", NumCode = "752", Name = "Swedish krona/kronor" },
                new CurrencyCode { Code = "SGD", NumCode = "702", Name = "Singapore dollar" },
                new CurrencyCode { Code = "SHP", NumCode = "654", Name = "Saint Helena pound" },
                new CurrencyCode { Code = "SLL", NumCode = "694", Name = "Sierra Leonean leone" },
                new CurrencyCode { Code = "SOS", NumCode = "706", Name = "Somali shilling" },
                new CurrencyCode { Code = "SRD", NumCode = "968", Name = "Surinamese dollar" },
                new CurrencyCode { Code = "STD", NumCode = "678", Name = "Sao Tomé and Príncipe dobra" },
                new CurrencyCode { Code = "SYP", NumCode = "760", Name = "Syrian pound" },
                new CurrencyCode { Code = "SZL", NumCode = "748", Name = "Lilangeni" },
                new CurrencyCode { Code = "THB", NumCode = "764", Name = "Thai baht" },
                new CurrencyCode { Code = "TJS", NumCode = "972", Name = "Tajikistani somoni" },
                new CurrencyCode { Code = "TMT", NumCode = "934", Name = "Turkmenistani manat" },
                new CurrencyCode { Code = "TND", NumCode = "788", Name = "Tunisian dinar" },
                new CurrencyCode { Code = "TOP", NumCode = "776", Name = "Tongan pa‘anga" },
                new CurrencyCode { Code = "TRY", NumCode = "949", Name = "Turkish lira" },
                new CurrencyCode { Code = "TTD", NumCode = "780", Name = "Trinidad and Tobago dollar" },
                new CurrencyCode { Code = "TWD", NumCode = "901", Name = "New Taiwan dollar" },
                new CurrencyCode { Code = "TZS", NumCode = "834", Name = "Tanzanian shilling" },
                new CurrencyCode { Code = "UAH", NumCode = "980", Name = "Ukrainian hryvnia" },
                new CurrencyCode { Code = "UGX", NumCode = "800", Name = "Ugandan shilling" },
                new CurrencyCode { Code = "USD", NumCode = "840", Name = "United States dollar" },
                new CurrencyCode { Code = "USN", NumCode = "997", Name = "United States dollar (next day) (funds code)" },
                new CurrencyCode { Code = "USS", NumCode = "998", Name = "United States dollar (same day) (funds code) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)" },
                new CurrencyCode { Code = "UYU", NumCode = "858", Name = "Uruguayan peso" },
                new CurrencyCode { Code = "UZS", NumCode = "860", Name = "Uzbekistan som" },
                new CurrencyCode { Code = "VEF", NumCode = "937", Name = "Venezuelan bolívar fuerte" },
                new CurrencyCode { Code = "VND", NumCode = "704", Name = "Vietnamese ð?ng" },
                new CurrencyCode { Code = "VUV", NumCode = "548", Name = "Vanuatu vatu" },
                new CurrencyCode { Code = "WST", NumCode = "882", Name = "Samoan tala" },
                new CurrencyCode { Code = "XAF", NumCode = "950", Name = "CFA franc BEAC" },
                new CurrencyCode { Code = "XAG", NumCode = "961", Name = "Silver (one troy ounce)" },
                new CurrencyCode { Code = "XAU", NumCode = "959", Name = "Gold (one troy ounce)" },
                new CurrencyCode { Code = "XBA", NumCode = "955", Name = "European Composite Unit (EURCO) (bond market unit)" },
                new CurrencyCode { Code = "XBB", NumCode = "956", Name = "European Monetary Unit (E.M.U.-6) (bond market unit)" },
                new CurrencyCode { Code = "XBC", NumCode = "957", Name = "European Unit of Account 9 (E.U.A.-9) (bond market unit)" },
                new CurrencyCode { Code = "XBD", NumCode = "958", Name = "European Unit of Account 17 (E.U.A.-17) (bond market unit)" },
                new CurrencyCode { Code = "XCD", NumCode = "951", Name = "East Caribbean dollar" },
                new CurrencyCode { Code = "XDR", NumCode = "960", Name = "Special Drawing Rights" },
                new CurrencyCode { Code = "XFU", NumCode = "Nil", Name = "UIC franc (special settlement currency)" },
                new CurrencyCode { Code = "XOF", NumCode = "952", Name = "CFA Franc BCEAO" },
                new CurrencyCode { Code = "XPD", NumCode = "964", Name = "Palladium (one troy ounce)" },
                new CurrencyCode { Code = "XPF", NumCode = "953", Name = "CFP franc" },
                new CurrencyCode { Code = "XPT", NumCode = "962", Name = "Platinum (one troy ounce)" },
                new CurrencyCode { Code = "XTS", NumCode = "963", Name = "Code reserved for testing purposes" },
                new CurrencyCode { Code = "XXX", NumCode = "999", Name = "No currency" },
                new CurrencyCode { Code = "YER", NumCode = "886", Name = "Yemeni rial" },
                new CurrencyCode { Code = "ZAR", NumCode = "710", Name = "South African rand" },
                new CurrencyCode { Code = "ZMK", NumCode = "894", Name = "Zambian kwacha" },
                new CurrencyCode { Code = "ZWL", NumCode = "932", Name = "Zimbabwe dollar" },
                new CurrencyCode { Code = "SVC", NumCode = "222", Name = "EL SALVADOR COLON" },
                new CurrencyCode { Code = "GWP", NumCode = "624", Name = "GUINEA-BISSAU PESO" },
                new CurrencyCode { Code = "SKK", NumCode = "703", Name = "SLOVAK KORUNA" },
                new CurrencyCode { Code = "SIT", NumCode = "705", Name = "SLOVENIAN TOLAR" },
                new CurrencyCode { Code = "CNX", NumCode = "158", Name = "CHINESE RENMINBI" },
                new CurrencyCode { Code = "NNN", NumCode = "157", Name = "Nieznana" },
                new CurrencyCode { Code = "NN1", NumCode = "967", Name = "Nieznana" }
                );

            context.Cryteria.AddOrUpdate(c => c.Name,
                new CryteriaMC { Name = "IRD_L3", Region = "INTRACOUNTRY", Description = "", Product = "MCC, DMC", Ird = "L3", Fee = 0, IFNumber = 1, IFBase = 0, DeviationReg1 = 0, DeviationReg2 = 0, DeviationReg3 = 0, DeviationIF = 0.01m, DeviationIFMin = 0.001m, IsActive = false },
                new CryteriaMC { Name = "IRD_62", Region = "INTERREGIONAL", Description = "", Product = "MCC, DMC", Ird = "62", Fee = 0, IFNumber = 1, IFBase = 0, DeviationReg1 = 0, DeviationReg2 = 0, DeviationReg3 = 0, DeviationIF = 0.5m, DeviationIFMin = 0.001m, IsActive = true }
                );
        }
    }
}
