//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long AddressId { get; set; }
        public long PersonId { get; set; }
        public string AddressType { get; set; }
        public string CountryCode { get; set; }
        public string Region { get; set; }
        public string Region2 { get; set; }
        public string Region3 { get; set; }
        public string Street { get; set; }
        public string HouseNo { get; set; }
        public string LocalNo { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string PostOffice { get; set; }
        public bool IsFinacial { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
