//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentType
    {
        public int Id { get; set; }
        public int Order { get; set; }
        public string OrganizationId { get; set; }
        public string StageCode { get; set; }
        public string AdjustmentType1 { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
