//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affection
    {
        public long AffectionId { get; set; }
        public string CaseId { get; set; }
        public string UserLogin { get; set; }
        public System.DateTimeOffset StartDate { get; set; }
        public Nullable<System.DateTimeOffset> EndDate { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
        public string UserFullName { get; set; }
    
        public virtual Complaint Complaint { get; set; }
    }
}
