//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINList
    {
        public string BIN { get; set; }
        public string ICA { get; set; }
        public string OrganizationId { get; set; }
        public string Member { get; set; }
        public string SourceCountryCode { get; set; }
        public string ParticipantId { get; set; }
        public Nullable<bool> ProductionStatus { get; set; }
        public Nullable<bool> CRBReport { get; set; }
        public Nullable<int> DocumentProcessStatus { get; set; }
        public System.DateTimeOffset ValidFrom { get; set; }
        public Nullable<System.DateTimeOffset> ValidTo { get; set; }
        public string BusinessLine { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
