//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseFilingIncomingBulkFile
    {
        public int FileId { get; set; }
        public string Name { get; set; }
        public string OrganizationId { get; set; }
        public Nullable<System.Guid> ProcessKey { get; set; }
        public Nullable<System.Guid> stream_id { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<System.DateTime> ProcesingStart { get; set; }
        public Nullable<System.DateTime> ProcesingFinished { get; set; }
        public bool ErrorFlag { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
