//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseFilingIncomingFileDocumentItem
    {
        public long CaseFilingIncomingFileDocumentItemId { get; set; }
        public long IncomingId { get; set; }
        public long DocumentId { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual ComplaintDocument ComplaintDocument { get; set; }
        public virtual CaseFilingIncomingFile CaseFilingIncomingFile { get; set; }
    }
}
