//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseFilingRecord
    {
        public long CaseFilingRecordId { get; set; }
        public string CaseId { get; set; }
        public long StageId { get; set; }
        public Nullable<long> OutgoingId { get; set; }
        public Nullable<long> IncomingId { get; set; }
        public string CaseType { get; set; }
        public Nullable<System.DateTimeOffset> ResponseDueDate { get; set; }
        public string ResponseCode { get; set; }
        public string ViolationCode { get; set; }
        public string CBReferenceNumber { get; set; }
        public string MasterCardCaseID { get; set; }
        public string PrimaryAccountNumber { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<System.DateTime> UnjustEnrichmentChargebackDate { get; set; }
        public Nullable<System.DateTime> UnjustEnrichmentCreditDate { get; set; }
        public Nullable<System.DateTime> ViolationDate { get; set; }
        public Nullable<System.DateTime> RebuttalDate { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public string MemoText { get; set; }
        public string FilingICA { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string FiledAgainstICA { get; set; }
        public Nullable<System.DateTime> EscalationDate { get; set; }
        public Nullable<System.DateTime> WithdrawnDate { get; set; }
        public Nullable<decimal> CaseFee { get; set; }
        public Nullable<decimal> FilingFee { get; set; }
        public Nullable<decimal> TechFee { get; set; }
        public Nullable<decimal> HubsiteFee { get; set; }
        public Nullable<decimal> AdminFee { get; set; }
        public Nullable<decimal> AppealFee { get; set; }
        public Nullable<decimal> WithdrawingFee { get; set; }
        public Nullable<decimal> PreArbFee { get; set; }
        public string CurrencyCode { get; set; }
        public string FilingRegion { get; set; }
        public string FiledAgainstRegion { get; set; }
        public Nullable<System.DateTime> CreditDate { get; set; }
        public string Ruling { get; set; }
        public Nullable<System.DateTime> RulingDate { get; set; }
        public Nullable<decimal> RulingAmount { get; set; }
        public string RulingCurrencyCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> CaseReceiver { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual CaseFilingIncomingFile CaseFilingIncomingFile { get; set; }
        public virtual CaseFilingOutgoingFile CaseFilingOutgoingFile { get; set; }
    }
}
