//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseFilingIncomingFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaseFilingIncomingFile()
        {
            this.CaseFilingIncomingFileDocumentItems = new HashSet<CaseFilingIncomingFileDocumentItem>();
            this.CaseFilingRecords = new HashSet<CaseFilingRecord>();
            this.FilesStageNotifications = new HashSet<FilesStageNotification>();
        }
    
        public long IncomingId { get; set; }
        public string CaseId { get; set; }
        public long StageId { get; set; }
        public System.Guid stream_id { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string FileContent { get; set; }
        public System.Guid ProcessKey { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingIncomingFileDocumentItem> CaseFilingIncomingFileDocumentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingRecord> CaseFilingRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesStageNotification> FilesStageNotifications { get; set; }
    }
}
