//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaint()
        {
            this.Affections = new HashSet<Affection>();
            this.Audits = new HashSet<Audit>();
            this.CaseFilingIncomingFiles = new HashSet<CaseFilingIncomingFile>();
            this.CaseFilingOutgoingFiles = new HashSet<CaseFilingOutgoingFile>();
            this.CaseFilingRecords = new HashSet<CaseFilingRecord>();
            this.ComplaintAutomaticEvents = new HashSet<ComplaintAutomaticEvent>();
            this.ComplaintDocuments = new HashSet<ComplaintDocument>();
            this.ComplaintFinacialBalances = new HashSet<ComplaintFinacialBalance>();
            this.ComplaintNotes = new HashSet<ComplaintNote>();
            this.ComplaintRecords = new HashSet<ComplaintRecord>();
            this.ComplaintStages = new HashSet<ComplaintStage>();
            this.ComplaintStageDocuments = new HashSet<ComplaintStageDocument>();
            this.ComplaintSuspendeds = new HashSet<ComplaintSuspended>();
            this.ComplaintValues = new HashSet<ComplaintValue>();
            this.DocumentExports = new HashSet<DocumentExport>();
            this.FilesStageNotifications = new HashSet<FilesStageNotification>();
            this.FilesStageNotifications1 = new HashSet<FilesStageNotification>();
            this.Representments = new HashSet<Representment>();
        }
    
        public string CaseId { get; set; }
        public string BIN { get; set; }
        public string OrganizationId { get; set; }
        public Nullable<long> IncomingId { get; set; }
        public Nullable<System.DateTimeOffset> IncomingDate { get; set; }
        public Nullable<long> PostTranId { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public string ARN { get; set; }
        public string PANMask { get; set; }
        public string PANHash { get; set; }
        public string PANExpirationDateMonth { get; set; }
        public string PANExpirationDateYear { get; set; }
        public string ACode { get; set; }
        public string TransactionAmountSign { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public Nullable<System.DateTimeOffset> TransactionDate { get; set; }
        public string BrandName { get; set; }
        public string MessageType { get; set; }
        public string ReasonCode { get; set; }
        public string MID { get; set; }
        public string POSEntryMode { get; set; }
        public string DocumentationIndicator { get; set; }
        public string ECommerce { get; set; }
        public Nullable<bool> Is3DSecure { get; set; }
        public Nullable<int> C3DSCAVVStatus { get; set; }
        public Nullable<int> ProcessingStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTimeOffset> StatusDate { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.DateTimeOffset> CloseDate { get; set; }
        public string SourceCountryCode { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<bool> PostilionData { get; set; }
        public string ParticipantId { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Affection> Affections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingIncomingFile> CaseFilingIncomingFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingOutgoingFile> CaseFilingOutgoingFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingRecord> CaseFilingRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintAutomaticEvent> ComplaintAutomaticEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintDocument> ComplaintDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintFinacialBalance> ComplaintFinacialBalances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintNote> ComplaintNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintRecord> ComplaintRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStage> ComplaintStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStageDocument> ComplaintStageDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintSuspended> ComplaintSuspendeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintValue> ComplaintValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentExport> DocumentExports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesStageNotification> FilesStageNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesStageNotification> FilesStageNotifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Representment> Representments { get; set; }
    }
}
