//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintValue
    {
        public long ValueId { get; set; }
        public string CaseId { get; set; }
        public Nullable<long> StageId { get; set; }
        public Nullable<long> IncomingId { get; set; }
        public string StageAmountSign { get; set; }
        public Nullable<decimal> StageAmount { get; set; }
        public string StageCurrencyCode { get; set; }
        public string BookingAmountSign { get; set; }
        public Nullable<decimal> BookingAmount { get; set; }
        public string BookingCurrencyCode { get; set; }
        public Nullable<bool> IsPartial { get; set; }
        public string DebitCredit { get; set; }
        public string EuroBookingAmountSign { get; set; }
        public Nullable<decimal> EuroBookingAmount { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
    }
}
