//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintFinacialBalance
    {
        public long FinacialBalanceId { get; set; }
        public string CaseId { get; set; }
        public long StageId { get; set; }
        public Nullable<long> InternalStageId { get; set; }
        public string MID { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string CurrencyCodeAmount { get; set; }
        public Nullable<decimal> EuroDebitAmount { get; set; }
        public Nullable<decimal> EuroCreditAmount { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public Nullable<bool> IsPartial { get; set; }
        public Nullable<System.DateTime> FinacialDate { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual ComplaintStage ComplaintStage { get; set; }
    }
}
