//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintStage()
        {
            this.ComplaintFinacialBalances = new HashSet<ComplaintFinacialBalance>();
            this.ComplaintStageInternals = new HashSet<ComplaintStageInternal>();
            this.FilesStageNotifications = new HashSet<FilesStageNotification>();
        }
    
        public long StageId { get; set; }
        public string CaseId { get; set; }
        public Nullable<long> IncomingId { get; set; }
        public Nullable<System.DateTimeOffset> IncomingDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<bool> DocumentationIndicator { get; set; }
        public Nullable<int> DefinitionStageId { get; set; }
        public string StageCode { get; set; }
        public string StageDescription { get; set; }
        public Nullable<System.DateTimeOffset> StageDate { get; set; }
        public Nullable<System.DateTimeOffset> StageEndDate { get; set; }
        public string MemberMessageText { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTimeOffset> StatusDate { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintFinacialBalance> ComplaintFinacialBalances { get; set; }
        public virtual StageDefinition StageDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStageInternal> ComplaintStageInternals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilesStageNotification> FilesStageNotifications { get; set; }
    }
}
