//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintRecord
    {
        public long RecordId { get; set; }
        public string CaseId { get; set; }
        public Nullable<long> StageId { get; set; }
        public Nullable<long> IncomingId { get; set; }
        public string MTI { get; set; }
        public string FunctionCode { get; set; }
        public string MessageReversalIndicator { get; set; }
        public string TransactionCode { get; set; }
        public string MCC { get; set; }
        public string PosTerminalType { get; set; }
        public string PosCardDataInputMode { get; set; }
        public string PosCardPresent { get; set; }
        public string PosCardholderPresent { get; set; }
        public string PosCardholderAuthMethod { get; set; }
        public Nullable<System.DateTimeOffset> GiccRevDate { get; set; }
        public Nullable<decimal> SettleAmountImpact { get; set; }
        public Nullable<decimal> TranAmountReq { get; set; }
        public Nullable<long> PrevPostTranId { get; set; }
        public string StageCode { get; set; }
        public Nullable<System.DateTimeOffset> StageDate { get; set; }
        public string Narritive { get; set; }
        public string ControlNr { get; set; }
        public string DestinationInstitutionId { get; set; }
        public string MsgTypeId { get; set; }
        public string ReasonCode { get; set; }
        public string ResponseCode { get; set; }
        public string MemoText { get; set; }
        public string SystemTraceAuditNr { get; set; }
        public Nullable<System.DateTime> DatetimeTranLocal { get; set; }
        public string ExpiryDate { get; set; }
        public string MerchantType { get; set; }
        public string POSEntryMode { get; set; }
        public string CardSeqNr { get; set; }
        public string PosConditionCode { get; set; }
        public string RetrievalReferenceNr { get; set; }
        public string AuthIDRsp { get; set; }
        public string RspCodeRsp { get; set; }
        public string ServiceRestrictionCode { get; set; }
        public string TerminalID { get; set; }
        public string CardAcceptorIDCode { get; set; }
        public string CardAcceptorNameLoc { get; set; }
        public string PosCardDataInputAbility { get; set; }
        public string PosCardholderAuthAbility { get; set; }
        public string PosCardCaptureAbility { get; set; }
        public string PosOperatingEnvironment { get; set; }
        public string PosCardholderAuthEntity { get; set; }
        public string PosCardDataOutputAbility { get; set; }
        public string PosTerminalOutputAbility { get; set; }
        public string PosPinCaptureAbility { get; set; }
        public string PosTerminalOperator { get; set; }
        public string UcafData { get; set; }
        public string TranAmountRsp { get; set; }
        public string TranType { get; set; }
        public string ProcessingCode { get; set; }
        public string KKOCbReference { get; set; }
        public string TranLifeCycleID { get; set; }
        public string IRD { get; set; }
        public string AssignedID { get; set; }
        public string FraudNotificationDate { get; set; }
        public string TransactionId { get; set; }
        public string MultiClearingSeqNr { get; set; }
        public string MultiClearingSeqCnt { get; set; }
        public string AuthSourceCode { get; set; }
        public string AVSRspCode { get; set; }
        public string MarketSpecAuth { get; set; }
        public string AuthRspCode { get; set; }
        public string MessageType { get; set; }
        public string PrevMessageType { get; set; }
        public string PrevUcafData { get; set; }
        public string StructuredDataReq { get; set; }
        public Nullable<System.DateTime> DatetimeRsp { get; set; }
        public Nullable<int> InsertMode { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
    }
}
