//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintDocument()
        {
            this.CaseFilingIncomingFileDocumentItems = new HashSet<CaseFilingIncomingFileDocumentItem>();
            this.CaseFilingOutgoingFileDocumentItems = new HashSet<CaseFilingOutgoingFileDocumentItem>();
            this.ComplaintStageDocuments = new HashSet<ComplaintStageDocument>();
            this.DocumentExports = new HashSet<DocumentExport>();
        }
    
        public long DocumentId { get; set; }
        public string CaseId { get; set; }
        public Nullable<long> StageId { get; set; }
        public System.Guid stream_id { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string SourceFileName { get; set; }
        public string SourceIncoming { get; set; }
        public bool Incoming { get; set; }
        public bool Manual { get; set; }
        public Nullable<bool> IsAutomatic { get; set; }
        public bool Export { get; set; }
        public Nullable<int> ExportStatus { get; set; }
        public Nullable<System.DateTimeOffset> ExportDate { get; set; }
        public string ExportUser { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingIncomingFileDocumentItem> CaseFilingIncomingFileDocumentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFilingOutgoingFileDocumentItem> CaseFilingOutgoingFileDocumentItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStageDocument> ComplaintStageDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentExport> DocumentExports { get; set; }
    }
}
