//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRBReportItem
    {
        public long ItemId { get; set; }
        public string CaseId { get; set; }
        public Nullable<long> ValueId { get; set; }
        public Nullable<long> RecordsId { get; set; }
        public Nullable<long> StageId { get; set; }
        public Nullable<int> CBReportStatus { get; set; }
        public Nullable<int> CRBReportId { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual CRBReport CRBReport { get; set; }
    }
}
