//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRBReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRBReport()
        {
            this.CRBReportItems = new HashSet<CRBReportItem>();
        }
    
        public int CRBReportId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> stream_id { get; set; }
        public int CurrentYear { get; set; }
        public int NumberInCurrentYear { get; set; }
        public int NumberOfDetailRecords { get; set; }
        public Nullable<System.Guid> ProcessKey { get; set; }
        public System.DateTimeOffset ProcesingStart { get; set; }
        public System.DateTimeOffset ProcesingFinished { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRBReportItem> CRBReportItems { get; set; }
    }
}
