//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentExportReference
    {
        public long DocumentExportReferenceId { get; set; }
        public long DocumentExportId { get; set; }
        public long DocumentExportExtractId { get; set; }
    
        public virtual DocumentExport DocumentExport { get; set; }
        public virtual DocumentExtractExport DocumentExtractExport { get; set; }
    }
}
