//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentExport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentExport()
        {
            this.DocumentExportReferences = new HashSet<DocumentExportReference>();
        }
    
        public long DocumentExportId { get; set; }
        public string CaseId { get; set; }
        public string OrganizationId { get; set; }
        public long DocumentId { get; set; }
        public string StageCode { get; set; }
        public string Description { get; set; }
        public string ExportCode { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual Complaint Complaint { get; set; }
        public virtual ComplaintDocument ComplaintDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentExportReference> DocumentExportReferences { get; set; }
    }
}
