//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeCollectionExtract
    {
        public long FeeCollectionExtractId { get; set; }
        public Nullable<System.Guid> ProcessKey { get; set; }
        public string CaseId { get; set; }
        public long FeeCollectionId { get; set; }
        public Nullable<long> FeeCollectionPostilionFileId { get; set; }
        public string ControlNr { get; set; }
        public string PostilionExtractClearString { get; set; }
        public string PostilionExtractWithBase64String { get; set; }
        public string PostilionStatus { get; set; }
        public string PostilionStatusMessage { get; set; }
        public Nullable<bool> ErrorFlag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual FeeCollection FeeCollection { get; set; }
        public virtual FeeCollectionPostilionFile FeeCollectionPostilionFile { get; set; }
    }
}
