//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeType()
        {
            this.GoodFaithLetterRecords = new HashSet<GoodFaithLetterRecord>();
        }
    
        public int FeeTypeId { get; set; }
        public string Value { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodFaithLetterRecord> GoodFaithLetterRecords { get; set; }
    }
}
