//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesEndPointDefinition
    {
        public int DefinitionId { get; set; }
        public string OrganizationId { get; set; }
        public string EndPointName { get; set; }
        public string BIN { get; set; }
        public string EndPointDirectoryName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
