//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodFaithLetter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodFaithLetter()
        {
            this.GoodFaithLetterRecords = new HashSet<GoodFaithLetterRecord>();
            this.GoodFaithLetterStages = new HashSet<GoodFaithLetterStage>();
            this.GoodFaithLetterValues = new HashSet<GoodFaithLetterValue>();
        }
    
        public string CaseId { get; set; }
        public string CountryCode { get; set; }
        public string BIN { get; set; }
        public string OrganizationId { get; set; }
        public string PANMask { get; set; }
        public string PANHash { get; set; }
        public string PANNameCardHolder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTimeOffset> StatusDate { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.DateTimeOffset> CloseDate { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodFaithLetterRecord> GoodFaithLetterRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodFaithLetterStage> GoodFaithLetterStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodFaithLetterValue> GoodFaithLetterValues { get; set; }
    }
}
