//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodFaithLetterRecord
    {
        public long RecordId { get; set; }
        public string CaseId { get; set; }
        public long StageId { get; set; }
        public string Cdb_CaseId { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public string DestinationInstitutionId { get; set; }
        public string ControlNr { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual GoodFaithLetter GoodFaithLetter { get; set; }
        public virtual FeeType FeeType { get; set; }
        public virtual GoodFaithLetterStage GoodFaithLetterStage { get; set; }
    }
}
