//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingTranMASTERCARD
    {
        public long IncomingId { get; set; }
        public string CaseId { get; set; }
        public string ARN { get; set; }
        public string PANHash { get; set; }
        public string ACode { get; set; }
        public string IncomingDate { get; set; }
        public string SettlementDate { get; set; }
        public string TransactionDate { get; set; }
        public string ProcessingDate { get; set; }
        public string FunctionCode { get; set; }
        public string ReasonCode { get; set; }
        public string MCC { get; set; }
        public string MTI { get; set; }
        public string MessageReversalIndicator { get; set; }
        public string RetrievalReferenceNumber { get; set; }
        public string POSID { get; set; }
        public string OriginalTransactionAmount { get; set; }
        public string OriginalTransactionReconciliation { get; set; }
        public string BookingAmountSign { get; set; }
        public string BookingAmount { get; set; }
        public string BookingAmountExponent { get; set; }
        public string BookingCurrencyCode { get; set; }
        public string StageAmountSign { get; set; }
        public string StageAmount { get; set; }
        public string StageAmountExponent { get; set; }
        public string StageCurrencyCode { get; set; }
        public string MerchantNameCity { get; set; }
        public string MerchantCapability { get; set; }
        public string CardAcceptorCountryCode { get; set; }
        public string MemberMessageText { get; set; }
        public string KKOCbReference { get; set; }
        public string MRI { get; set; }
        public string PartialFlag { get; set; }
        public string ProcessingCode { get; set; }
        public string ServiceCode { get; set; }
        public string CurrencyExponents { get; set; }
        public string CurrencyCodesAmountsOriginal { get; set; }
        public string DataRecord { get; set; }
        public string DateAction { get; set; }
        public string ECSLI { get; set; }
        public string TerminalType { get; set; }
        public string InputMode { get; set; }
        public string IssuerCountryCode { get; set; }
        public string Brand { get; set; }
        public string Narritive { get; set; }
        public string TransactionAmountSign { get; set; }
        public string TransactionAmount { get; set; }
        public string TransactionAmountExponent { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string Stage { get; set; }
        public string StageDate { get; set; }
        public string CVVFlag { get; set; }
        public string CVCFlag { get; set; }
        public string ECommerce { get; set; }
        public string MPILogFlag { get; set; }
        public string GiccMCC { get; set; }
        public string GiccDomesticMCC { get; set; }
        public string POSEntryMode { get; set; }
        public string DocumentationIndicator { get; set; }
        public string PosTerminalType { get; set; }
        public string PosCardDataImputMode { get; set; }
        public string PosCardPresent { get; set; }
        public string PosCardholderPresent { get; set; }
        public string PosCardholderAuthMethod { get; set; }
        public string ExpiryDate { get; set; }
        public string GiccRevDate { get; set; }
        public string TransactionDateTimeLocal { get; set; }
        public string SettleAmountImpact { get; set; }
        public string TranAmountReq { get; set; }
        public string PostTranId { get; set; }
        public string PrevPostTranId { get; set; }
        public string TranLifeCycleID { get; set; }
        public string IRD { get; set; }
        public string AssignedID { get; set; }
        public string FraudNotificationDate { get; set; }
        public string PosCardholderAuthEntity { get; set; }
        public string PosCardDataOutputAbility { get; set; }
        public string TransactionDestinationInstitutionIdCode { get; set; }
        public int FileId { get; set; }
        public Nullable<bool> ErrorFlag { get; set; }
        public int ProcessingStatus { get; set; }
        public string SourceCountryCode { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
