//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalStageDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternalStageDefinition()
        {
            this.ComplaintStageInternals = new HashSet<ComplaintStageInternal>();
            this.GoodFaithLetterStages = new HashSet<GoodFaithLetterStage>();
            this.RecoveryCardStages = new HashSet<RecoveryCardStage>();
        }
    
        public long InternalStageId { get; set; }
        public Nullable<int> StageDefinitionId { get; set; }
        public string InternalStageCode { get; set; }
        public bool Incoming { get; set; }
        public bool Manual { get; set; }
        public bool Direct { get; set; }
        public string Name { get; set; }
        public bool IsFinancial { get; set; }
        public bool IsRecoveryCard { get; set; }
        public bool IsGoodFaithLetter { get; set; }
        public bool Debit { get; set; }
        public bool Credit { get; set; }
        public string StageSign { get; set; }
        public string Action { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStageInternal> ComplaintStageInternals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodFaithLetterStage> GoodFaithLetterStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardStage> RecoveryCardStages { get; set; }
    }
}
