//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingValue
    {
        public int MappingId { get; set; }
        public string Field { get; set; }
        public string BaseValue { get; set; }
        public string MappingValue1 { get; set; }
    }
}
