//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationDefinition
    {
        public int MessageEventNamber { get; set; }
        public string MessageText { get; set; }
        public int MessageType { get; set; }
        public string MailingGroups { get; set; }
        public Nullable<bool> SendNotification { get; set; }
        public Nullable<System.DateTimeOffset> InsertDate { get; set; }
        public string InsertUser { get; set; }
    }
}
