//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public string OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationPrefix { get; set; }
        public string SettlementCurrencyCode { get; set; }
    }
}
