//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParserKey
    {
        public int KeyId { get; set; }
        public string OrganizationId { get; set; }
        public string Key { get; set; }
        public string KeyValue { get; set; }
        public int AddLenght { get; set; }
    }
}
