//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryCardStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecoveryCardStage()
        {
            this.RecoveryCardRecords = new HashSet<RecoveryCardRecord>();
            this.RecoveryCardValues = new HashSet<RecoveryCardValue>();
        }
    
        public long StageId { get; set; }
        public string CaseId { get; set; }
        public Nullable<long> InternalStageDefinitionId { get; set; }
        public string InternalStageCode { get; set; }
        public Nullable<System.DateTimeOffset> StageDate { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual RecoveryCard RecoveryCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardRecord> RecoveryCardRecords { get; set; }
        public virtual InternalStageDefinition InternalStageDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardValue> RecoveryCardValues { get; set; }
    }
}
