//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecoveryCard()
        {
            this.RecoveryCardLists = new HashSet<RecoveryCardList>();
            this.RecoveryCardNotes = new HashSet<RecoveryCardNote>();
            this.RecoveryCardRecords = new HashSet<RecoveryCardRecord>();
            this.RecoveryCardStages = new HashSet<RecoveryCardStage>();
            this.RecoveryCardValues = new HashSet<RecoveryCardValue>();
        }
    
        public string CaseId { get; set; }
        public string CountryCode { get; set; }
        public string BIN { get; set; }
        public string OrganizationId { get; set; }
        public string PANMask { get; set; }
        public string PANHash { get; set; }
        public string PANExpirationDateMonth { get; set; }
        public string PANExpirationDateYear { get; set; }
        public string PANNameCardHolder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTimeOffset> StatusDate { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.DateTimeOffset> CloseDate { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardList> RecoveryCardLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardNote> RecoveryCardNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardRecord> RecoveryCardRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardStage> RecoveryCardStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecoveryCardValue> RecoveryCardValues { get; set; }
    }
}
