//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryCardRecord
    {
        public long RecordId { get; set; }
        public string CaseId { get; set; }
        public long StageId { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<bool> IsSign { get; set; }
        public Nullable<bool> FakeCard { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<System.DateTimeOffset> CardSentToIssuerDate { get; set; }
        public string Cdb_CaseId { get; set; }
        public Nullable<int> FeeTypeId { get; set; }
        public Nullable<int> PickupTypeId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTimeOffset> TransactionDateTime { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public string MCC { get; set; }
        public string MID { get; set; }
        public string OID { get; set; }
        public string TID { get; set; }
        public string MIDName { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string ResponseCode { get; set; }
        public string DestinationInstitutionId { get; set; }
        public string ControlNr { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        public virtual RecoveryCard RecoveryCard { get; set; }
        public virtual RecoveryCardStage RecoveryCardStage { get; set; }
    }
}
