//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StageDefinition()
        {
            this.ComplaintStages = new HashSet<ComplaintStage>();
        }
    
        public int StageId { get; set; }
        public string StageCode { get; set; }
        public bool Incoming { get; set; }
        public bool Manual { get; set; }
        public bool Direct { get; set; }
        public bool DirectVisa { get; set; }
        public bool DirectMasterCard { get; set; }
        public Nullable<int> DocumentProcess { get; set; }
        public Nullable<int> DayStepMC { get; set; }
        public Nullable<int> DayStepVISA { get; set; }
        public Nullable<int> DayStepCLF { get; set; }
        public string Name { get; set; }
        public bool Debit { get; set; }
        public bool Credit { get; set; }
        public Nullable<bool> IsFinancial { get; set; }
        public string StageSign { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public System.DateTimeOffset InsertDate { get; set; }
        public string InsertUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintStage> ComplaintStages { get; set; }
    }
}
