//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CBT_KLIENCI
    {
        public string KLN_NAZWA { get; set; }
        public string KLN_NAZWA_SKROCONA { get; set; }
        public Nullable<decimal> KLN_KLN_ID { get; set; }
        public string KLN_MID { get; set; }
        public System.DateTime KLN_DATA_REJESTRACJI { get; set; }
        public string KLN_POZIOM { get; set; }
        public string KLN_MCC_VISA { get; set; }
        public string KLN_NR_PUNKTU { get; set; }
        public Nullable<decimal> KLN_SALDO { get; set; }
        public string KLN_CZY_MOZNA_WDZ { get; set; }
        public string KLN_CZY_VIP { get; set; }
        public string KLN_CZY_WYSLANY_DO_POSTILIONA { get; set; }
        public string KLN_NIP { get; set; }
        public string KLN_MCC_MC { get; set; }
        public string KLN_REGON { get; set; }
        public string KLN_MCC_EURO { get; set; }
        public string KLN_KONSOLIDACJA_RAPORTU { get; set; }
        public Nullable<decimal> KLN_POR_ID { get; set; }
        public Nullable<decimal> KLN_TWN_ID { get; set; }
        public string KLN_FUNKCJA { get; set; }
        public string KLN_KOD_REGIONU { get; set; }
        public string KLN_KOD_ZAMKNIECIA { get; set; }
        public decimal KLN_ID { get; set; }
        public string KLN_CZY_ARCHIWALNE { get; set; }
        public System.DateTime KLN_KIEDY_UTWORZYL { get; set; }
        public string KLN_KTO_MODYFIKOWAL { get; set; }
        public Nullable<System.DateTime> KLN_KIEDY_MODYFIKOWAL { get; set; }
        public string KLN_KTO_UTWORZYL { get; set; }
        public string KLN_CZY_PILNY { get; set; }
        public string KLN_PROP_OPLATA_PROW { get; set; }
        public Nullable<System.DateTime> KLN_DATA_ZATWIERDZENIA { get; set; }
        public string KLN_UMOWA_KRS { get; set; }
        public string KLN_UMOWA_SC { get; set; }
        public string KLN_RODZAJ_KLIENTA { get; set; }
        public string KLN_UWAGI { get; set; }
        public string KLN_WPIS_EWID_GOSP { get; set; }
        public Nullable<decimal> KLN_PRZ_ID_OPIEKUJE_SIE { get; set; }
        public Nullable<decimal> KLN_PRZ_ID { get; set; }
        public Nullable<decimal> KLN_PRZ_ID_POZYSKANY_PRZEZ { get; set; }
        public string KLN_ZAMKNIECIE_DNIA_DO { get; set; }
        public string KLN_NR_LINII_POS { get; set; }
        public string KLN_CZY_TON { get; set; }
        public Nullable<System.DateTime> KLN_DATA_AKTYWACJI_LOJALNOSC { get; set; }
        public string KLN_ZAMKNIECIE_DNIA_OD { get; set; }
        public string KLN_TERMIN_PLATNOSCI { get; set; }
        public string KLN_CZESTOTL_WYC { get; set; }
        public string KLN_WYJSCIE_NA_MIASTO { get; set; }
        public Nullable<System.DateTime> KLN_DATA_AKTYWACJI_AMEX { get; set; }
        public Nullable<decimal> KLN_MAKS_KWOTA_TRANS { get; set; }
        public Nullable<System.DateTime> KLN_DATA_AKTYWACJI_BILLBIRD { get; set; }
        public Nullable<System.DateTime> KLN_DATA_AKTYWACJI_FINPLUS { get; set; }
        public Nullable<System.DateTime> KLN_DATA_AKTYWACJI_POLKOMTEL { get; set; }
        public string KLN_STATUS { get; set; }
        public Nullable<decimal> KLN_PRC_ID { get; set; }
        public string KLN_CZY_MONITOROWANY { get; set; }
        public Nullable<decimal> KLN_LICZBA_TPS { get; set; }
        public string KLN_FUNKCJE { get; set; }
        public Nullable<decimal> KLN_CCP_ID { get; set; }
        public string KLN_WYSYL_INFO_AWARII { get; set; }
        public string KLN_PMT_FREQ { get; set; }
        public Nullable<decimal> KLN_PMT_DAYOFWEEK { get; set; }
        public Nullable<decimal> KLN_ON_PRESENT_PERC { get; set; }
        public string KLN_NR_UMOWY { get; set; }
        public string KLN_NUMER_AMEX { get; set; }
        public Nullable<System.DateTime> KLN_DATA_ZAMKNIECIA { get; set; }
        public string KLN_PRZYCZYNA_ODRZUCENIA { get; set; }
        public Nullable<System.DateTime> KLN_NUMER_AMEX_OD { get; set; }
        public string KLN_KTO_ZM_PLATNOSC { get; set; }
        public string KLN_NAZWA_GCO { get; set; }
        public Nullable<decimal> KLN_FLOOR_LIMIT { get; set; }
        public string KLN_CZY_KLUCZOWY { get; set; }
        public Nullable<decimal> KLN_QCARDS_NR { get; set; }
        public Nullable<decimal> KLN_PRZ_ID_OPIEKA_BIZNES { get; set; }
        public Nullable<decimal> KLN_STATEMENTMODE { get; set; }
        public string KLN_STATEMENTMODEDET { get; set; }
        public Nullable<decimal> KLN_PRZ_ID_OPIEKUJE_SIE2 { get; set; }
        public Nullable<decimal> KLN_ID_ECARD { get; set; }
        public string KLN_AMEX_POZYSKANIE { get; set; }
        public string KLN_NAZWA_GCO_CHB { get; set; }
        public string KLN_KOMPENSACJA_EJD { get; set; }
        public string KLN_ROUTING_GROUP { get; set; }
        public string KLN_NAZWA_FAKTURA { get; set; }
        public string KLN_KOD_PUNKTU { get; set; }
        public string KLN_SKROT { get; set; }
        public string KLN_NAZWA_SIECIOWA { get; set; }
        public Nullable<decimal> KLN_RODZAJ_KLN_PLATN { get; set; }
        public Nullable<decimal> KLN_PRZ_ID_OPIEKA_ZEW { get; set; }
        public string KLN_PIN { get; set; }
        public string KLN_MASTERCARD_ASSIGNED_ID { get; set; }
        public string KLN_NAZWA_GEOLOKALIZACJA { get; set; }
        public string KLN_PREF_MASTERCARD { get; set; }
        public string KLN_MPK { get; set; }
        public string KLN_PREF_VISA { get; set; }
        public string KLN_ZM_OSOBOWOSCI_PRAWNEJ { get; set; }
        public string KLN_KRAJ_KOD { get; set; }
        public string KLN_MCC_DOMESTIC_VISA { get; set; }
        public string KLN_MCC_DOMESTIC_MC { get; set; }
        public string KLN_MCC_DOMESTIC_EURO { get; set; }
    }
}
