//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SELECTEDPOSTILIONDATA
    {
        public long post_tran_id { get; set; }
        public Nullable<int> post_tran_cust_id { get; set; }
        public Nullable<decimal> tran_amount_rsp { get; set; }
        public string tran_currency_code { get; set; }
        public Nullable<System.DateTime> datetime_tran_local { get; set; }
        public string structured_data_req { get; set; }
        public string card_verification_result { get; set; }
        public string pos_terminal_type { get; set; }
        public string alpha_code { get; set; }
        public string currency_code { get; set; }
        public Nullable<int> nr_decimals { get; set; }
        public string name { get; set; }
        public string tran_type { get; set; }
        public string extended_tran_type { get; set; }
        public string primary_file_reference { get; set; }
        public string message_type { get; set; }
        public string card_acceptor_id_code { get; set; }
        public string pan_reference { get; set; }
        public string auth_id_rsp { get; set; }
        public string ucaf_data { get; set; }
        public Nullable<System.DateTime> datetime_rsp { get; set; }
        public string terminal_id { get; set; }
        public string pos_card_present { get; set; }
        public string pos_cardholder_present { get; set; }
        public string pos_card_data_input_mode { get; set; }
        public string expiry_date { get; set; }
        public string pos_cardholder_auth_entity { get; set; }
        public string pos_card_data_output_ability { get; set; }
        public string pan { get; set; }
        public string pan_encrypted { get; set; }
        public string merchant_type { get; set; }
        public string card_acceptor_name_loc { get; set; }
        public string pos_entry_mode { get; set; }
        public string pos_cardholder_auth_method { get; set; }
        public Nullable<decimal> settle_amount_impact { get; set; }
        public Nullable<decimal> tran_amount_req { get; set; }
        public Nullable<int> prev_post_tran_id { get; set; }
        public string pos_condition_code { get; set; }
        public string retrieval_reference_nr { get; set; }
        public string rsp_code_rsp { get; set; }
        public Nullable<long> tran_nr { get; set; }
        public string card_seq_nr { get; set; }
        public string service_restriction_code { get; set; }
        public string pos_card_data_input_ability { get; set; }
        public string pos_cardholder_auth_ability { get; set; }
        public string pos_card_capture_ability { get; set; }
        public string pos_operating_environment { get; set; }
        public string pos_terminal_output_ability { get; set; }
        public string pos_pin_capture_ability { get; set; }
        public string pos_terminal_operator { get; set; }
        public string system_trace_audit_nr { get; set; }
    }
}
