//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_eservice_okp_ARDEF
    {
        public string fvb_high_key_bin_range { get; set; }
        public string fvb_reserved1 { get; set; }
        public string fvb_low_key_bin_range { get; set; }
        public string fvb_reserved2 { get; set; }
        public string fvb_issuer_bin { get; set; }
        public string fvb_check_digit_alghoritm { get; set; }
        public string fvb_account_number_length { get; set; }
        public string fvb_card_type { get; set; }
        public string fvb_usage { get; set; }
        public string fvb_processor_bin { get; set; }
        public string fvb_domain { get; set; }
        public string fvb_region { get; set; }
        public string fvb_country { get; set; }
        public string fvb_issuer_com_card_si { get; set; }
        public string fvb_technology_indicator { get; set; }
        public string fvb_ardef_region { get; set; }
        public string fvb_ardef_country { get; set; }
        public string fvb_com_card_level2 { get; set; }
        public string fvb_com_card_level3 { get; set; }
        public string fvb_com_card_pos { get; set; }
        public string fvb_com_card_vat { get; set; }
        public string fvb_cft_flag { get; set; }
        public string fvb_product_type_ext { get; set; }
        public string fvb_org_credit_mt { get; set; }
        public string fvb_org_credit_og { get; set; }
        public string fvb_product_id { get; set; }
        public string fvb_reserved3 { get; set; }
        public string fvb_test_indicator { get; set; }
        public string fvb_reserved4 { get; set; }
    }
}
