//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Complaints
    {
        public string CaseId { get; set; }
        public string OrganizationId { get; set; }
        public Nullable<long> IncomingId { get; set; }
        public Nullable<System.DateTimeOffset> IncomingDate { get; set; }
        public Nullable<long> PostTranId { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public string ARN { get; set; }
        public string PANMask { get; set; }
        public string PANHash { get; set; }
        public string PANExpirationDateMonth { get; set; }
        public string PANExpirationDateYear { get; set; }
        public string ACode { get; set; }
        public string TransactionAmountSign { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string TransactionCurrencyCode { get; set; }
        public Nullable<System.DateTimeOffset> TransactionDate { get; set; }
        public string BrandName { get; set; }
        public string MessageType { get; set; }
        public string ReasonCode { get; set; }
        public string MID { get; set; }
        public string POSEntryMode { get; set; }
        public string DocumentationIndicator { get; set; }
        public string ECommerce { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTimeOffset> StatusDate { get; set; }
        public string SourceCountryCode { get; set; }
        public string StageCode { get; set; }
        public Nullable<System.DateTimeOffset> StageDate { get; set; }
        public Nullable<System.DateTimeOffset> StageEndDate { get; set; }
        public string StageAmountSign { get; set; }
        public Nullable<decimal> StageAmount { get; set; }
        public string StageCurrencyCode { get; set; }
        public string BookingAmountSign { get; set; }
        public Nullable<decimal> BookingAmount { get; set; }
        public string BookingCurrencyCode { get; set; }
        public string EuroBookingAmountSign { get; set; }
        public Nullable<decimal> EuroBookingAmount { get; set; }
        public string MTI { get; set; }
        public string FunctionCode { get; set; }
        public string MessageReversalIndicator { get; set; }
        public string TransactionCode { get; set; }
        public string MCC { get; set; }
        public string PosTerminalType { get; set; }
        public string PosCardDataInputMode { get; set; }
        public string PosCardPresent { get; set; }
        public string PosCardholderPresent { get; set; }
        public string PosCardholderAuthMethod { get; set; }
        public Nullable<System.DateTimeOffset> GiccRevDate { get; set; }
        public Nullable<decimal> SettleAmountImpact { get; set; }
        public Nullable<decimal> TranAmountReq { get; set; }
        public Nullable<long> PrevPostTranId { get; set; }
        public string Narritive { get; set; }
        public long RecordId { get; set; }
        public long StageId { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string BIN { get; set; }
        public Nullable<bool> Is3DSecure { get; set; }
        public Nullable<int> ProcessingStatus { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.DateTimeOffset> CloseDate { get; set; }
        public Nullable<bool> IsPartial { get; set; }
        public string DebitCredit { get; set; }
        public Nullable<System.DateTimeOffset> StageIncomingDate { get; set; }
        public Nullable<System.DateTime> StageSettlementDate { get; set; }
        public Nullable<System.DateTime> StageBusinessDate { get; set; }
        public string StageReasonCode { get; set; }
        public Nullable<bool> StageDocumentationIndicator { get; set; }
        public string StageDescription { get; set; }
        public string MemberMessageText { get; set; }
    }
}
