//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_mcipm_ip0040t1
    {
        public string issuer_acct_range_low { get; set; }
        public string gcms_product_id { get; set; }
        public string issuer_acct_range_high { get; set; }
        public string card_program_id { get; set; }
        public string issuer_card_program_id_priority { get; set; }
        public string member_id { get; set; }
        public string product_type { get; set; }
        public string endpoint { get; set; }
        public string country_alpha { get; set; }
        public string country_numeric { get; set; }
        public string region { get; set; }
        public string product_class { get; set; }
        public string txn_routing_ind { get; set; }
        public string first_presentment_reassign_switch { get; set; }
        public string product_reassign_switch { get; set; }
        public string pcwb_opt_in_switch { get; set; }
        public string licensed_product_id { get; set; }
        public string paypass_mapping_service_ind { get; set; }
        public string account_level_participation_ind { get; set; }
        public string account_level_activation_date { get; set; }
        public string cardholder_bill_currency_default { get; set; }
        public string cardholder_bill_currency_exponent_default { get; set; }
        public string cardholder_bill_primary_currency { get; set; }
        public string chip_to_magstripe_conversion_service_indicator { get; set; }
        public string floor_exp_date { get; set; }
        public string co_brand_participation_switch { get; set; }
        public string spend_control_switch { get; set; }
        public string merchant_cleansing_service_participation { get; set; }
        public string merchant_cleansing_activation_date { get; set; }
        public string paypass_enabled_indicator { get; set; }
        public string rate_type_indicator { get; set; }
        public string psn_route_indicator { get; set; }
        public string cash_back_wo_purchase_ind { get; set; }
    }
}
