//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SL_KODY_POCZTOWE
    {
        public string KPO_KOD { get; set; }
        public string KPO_POWIAT { get; set; }
        public string KPO_WOJEWODZTWO { get; set; }
        public string KPO_POW_KOD { get; set; }
        public string KPO_WOJ_KOD { get; set; }
        public string KPO_POCZTA { get; set; }
        public string KPO_GMINA { get; set; }
        public string KPO_GMI_KOD { get; set; }
        public string KPO_KRAJ { get; set; }
    }
}
