//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CBT_ADRESY
    {
        public decimal ADR_ID { get; set; }
        public string ADR_E_MAIL { get; set; }
        public string ADR_WOJEWODZTWO { get; set; }
        public System.DateTime ADR_DATA_OD { get; set; }
        public Nullable<System.DateTime> ADR_DATA_DO { get; set; }
        public string ADR_KRAJ { get; set; }
        public string ADR_GMINA { get; set; }
        public string ADR_POWIAT { get; set; }
        public string ADR_NR_LOKALU { get; set; }
        public string ADR_NR_BUDYNKU { get; set; }
        public string ADR_MIEJSCOWOSC { get; set; }
        public string ADR_KOD_POCZTOWY { get; set; }
        public string ADR_ULICA { get; set; }
        public string ADR_TYP_ULICY { get; set; }
        public string ADR_RODZAJ { get; set; }
        public string ADR_NR_FAKSU { get; set; }
        public string ADR_TEL_STACJONARNY { get; set; }
        public string ADR_TEL_KOM { get; set; }
        public Nullable<decimal> ADR_PRZ_ID { get; set; }
        public Nullable<decimal> ADR_BNK_ID { get; set; }
        public Nullable<decimal> ADR_PRC_ID { get; set; }
        public Nullable<decimal> ADR_KLN_ID { get; set; }
        public string ADR_CZY_ARCHIWALNE { get; set; }
        public Nullable<System.DateTime> ADR_KIEDY_MODYFIKOWAL { get; set; }
        public System.DateTime ADR_KIEDY_UTWORZYL { get; set; }
        public string ADR_KTO_MODYFIKOWAL { get; set; }
        public string ADR_KTO_UTWORZYL { get; set; }
        public Nullable<decimal> ADR_ADR_ID { get; set; }
        public string ADR_CZY_AKTYWNY { get; set; }
        public Nullable<decimal> ADR_QCARDS_NR { get; set; }
        public string ADR_URL { get; set; }
        public string ADR_WOJ_KOD { get; set; }
        public string ADR_POW_KOD { get; set; }
        public string ADR_GMI_KOD { get; set; }
        public string ADR_KR_KOD { get; set; }
        public Nullable<decimal> ADR_SEQ2 { get; set; }
        public string ADR_REGION { get; set; }
        public string ADR_NAZWA_BUDYNKU { get; set; }
        public string ADR_SKRZYNKA_POCZTOWA { get; set; }
    }
}
