//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CBV_MIDBYTID
    {
        public string TID { get; set; }
        public string OID { get; set; }
        public string OID_NAME { get; set; }
        public string OID_HIERARCHY_LEVEL { get; set; }
        public string MID { get; set; }
        public string MID_HIERARCHY_LEVEL { get; set; }
        public string MCC { get; set; }
    }
}
