//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintTool.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplaintTool.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} extracted to bulk file {1}..
        /// </summary>
        public static string _1001 {
            get {
                return ResourceManager.GetString("_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk file {0} with file items: {1} was extracted successfully..
        /// </summary>
        public static string _1002 {
            get {
                return ResourceManager.GetString("_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notyfication {0} mail to: {1}.
        /// </summary>
        public static string _1003 {
            get {
                return ResourceManager.GetString("_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with the key {0}.
        /// </summary>
        public static string _1004 {
            get {
                return ResourceManager.GetString("_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} error : {1}.
        /// </summary>
        public static string _5001 {
            get {
                return ResourceManager.GetString("_5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error notyfication {0} mail to: {1}.
        /// </summary>
        public static string _5002 {
            get {
                return ResourceManager.GetString("_5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail error. {0}.
        /// </summary>
        public static string _5003 {
            get {
                return ResourceManager.GetString("_5003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No definition of mailing groups. Subject: {0}; Body: {1}.
        /// </summary>
        public static string _5004 {
            get {
                return ResourceManager.GetString("_5004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} of bulk file is corrupted - cannot create file by stream_id..
        /// </summary>
        public static string _5005 {
            get {
                return ResourceManager.GetString("_5005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP server error: {0}.
        /// </summary>
        public static string _5006 {
            get {
                return ResourceManager.GetString("_5006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found on key {0}.
        /// </summary>
        public static string _5007 {
            get {
                return ResourceManager.GetString("_5007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file error in saving as multipage: .
        /// </summary>
        public static string _501 {
            get {
                return ResourceManager.GetString("_501", resourceCulture);
            }
        }
    }
}
